export const REQUEST_APARTMENTS_PENDING = "REQUEST_APARTMENTS_PENDING";
export const REQUEST_APARTMENTS_SUCCESS = "REQUEST_APARTMENTS_SUCCESS";
export const REQUEST_APARTMENTS_FAILED = "REQUEST_APARTMENTS_FAILED";
export const RESET_APARTMENTS = "RESET_APARTMENTS";


const ApartmentActionTypes = {
    REQUEST_APARTMENTS_START: 'REQUEST_APARTMENTS_START',
    REQUEST_APARTMENTS_SUCCESS: 'REQUEST_APARTMENTS_SUCCESS',
    REQUEST_APARTMENTS_FAILURE: 'REQUEST_APARTMENTS_FAILURE',
    LIKE_APARTMENT: 'LIKE_APARTMENT',
    UNLIKE_APARTMENT: 'UNLIKE_APARTMENT'
};

export default ApartmentActionTypes;

